### ISSUE TITLE
[Suzu] Failed startup Device after few reboots (Device failed verification)

### ISSUE THREAD

**Issue by lubik1** [RiseOS/bug_tracker#24] opened 2018-12-02 12:34 UTC
**Device:** Suzu
**Kernel version:** 4.9.138
**Android version:** 9

**Description:**
After few reboots your system failed to startup (few times)

**How to reproduce:**
Just reboot it few times

**Logs:**
![fail](https://user-images.githubusercontent.com/19878552/49339781-6274e280-f63f-11e8-85ae-4717f9c16402.jpeg)

**Comment by Gray47Maxx** [comment] 2018-12-02 18:36
Confirmed. Also happens on Omni 9 and AOSP.

**Comment by danielgusvt** [comment] 2018-12-15 14:22
Fixed by https://github.com/sonyxperiadev/kernel/pull/1855?

**Comment by bartcubbins** [comment] 2018-12-18 16:46
the true reason has not been fixed, reboots remain, only restart reason was fixed

**Comment by bartcubbins** [comment] 2019-04-16 16:38
this issue still persist <s>and it caused by
https://github.com/bartcubbins/kernel_loire/commit/5a97f442572a7e8a4ecfaf81b0d39a1eb077ddc7</s>

**Comment by bartcubbins** [comment] 2019-04-27 13:37
fixed
https://github.com/bartcubbins/kernel_loire/commit/0747284a9a57dcec1b414df4fc46714451a085b4

**Closed as completed by bartcubbins** 2019-04-27 13:37 UTC
Labels: fixed
